### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by johndpope** [dribnet/clipit_old#3]
braceexpand
perlin_numpy

**Comment by johndpope** [comment]
pip3 install git+https://github.com/pvigier/perlin-numpy

**Comment by johndpope** [comment]
(torch) ➜  clipit git:(master) ✗ pip install CLIP
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: CLIP in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/clip-1.0-py3.8.egg (1.0)
Requirement already satisfied: ftfy in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from CLIP) (6.0.3)
Requirement already satisfied: regex in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from CLIP) (2021.4.4)
Requirement already satisfied: tqdm in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from CLIP) (4.56.0)
Requirement already satisfied: torch in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from CLIP) (1.8.0.dev20210208+cu110)
Requirement already satisfied: torchvision in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from CLIP) (0.9.0.dev20210211+cu110)
Requirement already satisfied: wcwidth in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from ftfy->CLIP) (0.2.5)
Requirement already satisfied: numpy in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from torch->CLIP) (1.21.0)
Requirement already satisfied: typing-extensions in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from torch->CLIP) (3.10.0.0)
Requirement already satisfied: pillow>=4.1.1 in /home/jp/miniconda3/envs/torch/lib/python3.8/site-packages (from torchvision->CLIP) (8.2.0)
(torch) ➜  clipit git:(master) ✗ python generate.py -p "fruit bowl pixelart"

/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
Traceback (most recent call last):
  File "generate.py", line 33, in <module>
    from CLIP import clip
ModuleNotFoundError: No module named 'CLIP'

**Comment by johndpope** [comment]
I think you need nerdy rodents install readme.

**Comment by dribnet** [comment]
thanks! yes, I haven't put any effort into maintaining the requirements so happy to accept a merge request for this that mostly matches what the colabs are using.
