### ISSUE TITLE
fyi - init_image

### ISSUE THREAD

**Issue by johndpope** [dribnet/clipit_old#4]
#@title Parameters
prompts = "trending on artstation" #@param {type:"string"}

#@markdown you can trade off speed for quality

quality = "best" #@param ["draft", "normal", "better", "best"]

#@markdown some people actually like square?  ¯\\_(ツ)_/¯

aspect = "square" #@param ["widescreen", "square"]
init_image = "1.jpeg"
#@markdown When you have the settings you want, press the play button on the left.
#@markdown The system will start drawing and show you results as it goes along.

#@markdown _(I can get "better" running on the colabs, but not "best".
#@markdown Sometimes it is necessary to "Restart Runtime" to clear memory.)_

# Simple setup from menu choices
import clipit
clipit.reset_settings()
clipit.add_settings(prompts=prompts, aspect=aspect, quality=quality,init_image=init_image)

# Optional: you could put extra settings here...

# Apply these settings and run
settings = clipit.apply_settings()
clipit.do_init(settings)
clipit.do_run(settings)

**Comment by dribnet** [comment]
PixelDraw does not currently support the init_image setting, only VQGAN does. It would be possible to support this though if there is interest.

**Comment by johndpope** [comment]
I see.

**Comment by dribnet** [comment]
or feel free to reopen as a feature request if you'd like to use init_image with pixeldraw. 😄

**Comment by johndpope** [comment]
gotcha.
