### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by Dango233** [dribnet/clipit_old#5]
With windows 10 + VS2017/2019 (I tried both), I got the folling error preventing me from installing diffvg.

```
 diffvg.cpp
c:\[...]\diffvg\pybind11\include\pybind11\cast.h(1405): error : too few arguments for template template pa
rameter "Tuple" [C:[...]\diffvg\build\temp.win-amd64-3.9\Release\diffvg.vcxproj]
            detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=
  std::pair, Ts=<T1, T2>]"
  (1483): here
```

Is there anyway to make this work...?

**Comment by dribnet** [comment]
Sorry - this appears to be a duplicate of BachiLi/diffvg#26 so you might try there as I am not familiar with that build process.

**Comment by surjikal** [comment]
@Dango233 I found something that worked for me, for this exact issue:
https://github.com/BachiLi/diffvg/issues/26#issuecomment-916625904
