### ISSUE TITLE
Repo is a fork, can't search

### ISSUE THREAD

**Issue by torridgristle** [dribnet/clipit_old#6]
Currently clipit is a fork so the code can't be searched and it won't show up in searches on Github either. It's not even similar to VQGAN-CLIP so it's definitely beyond the usual idea of a fork.

Before things progress too much further it'd be for the best if this was remade so it can be searched properly, it's making it difficult trying to find what controls the color of diffvg and where it is, and it'll only get worse.

**Comment by dribnet** [comment]
Thanks - that's pretty easy to do on my end (I think). @nerdyrodent - any objection if I cut the umbilical cord here?

**Comment by dribnet** [comment]
I've renamed this repo and created a new one with the same name and the switchover seems to be more or less working. Thanks.
